### ISSUE TITLE
Checklist about Damselfly and cm-model releases

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cm-damselfly#24]
@innodreamer (cc. @yunkon-kim @sykim-etri @ish-hcc @dev4unet)

안녕하세요. 

:date: Damselfly v0.2.x릴리스 일정을 11/13(수)로 계획하고 있습니다. 
* 컴퓨팅 인프라 소스/목표 모델 규격(스키마)의 개선 필요시 cm-model 개선 및 릴리스 추진이 필요하니 챙겨주시기 바랍니다.
* SW 소스/목표 모델 규격(스키마)에 대해서는 일단 초안 추가 및 테스트를 진행하면 될 것 같습니다. 이후, 릴리스 여부에 대해 의견을 주시거나 추진을 부탁드립니다.

:raising_hand: 먼저, 관련하여 이슈가 있으신 경우 댓글로 남겨주시기 바랍니다.

:ballot_box_with_check: 아래 사항들에 대해 추진을 부탁드리며, 완료된 항목들은 Checked 처리하여 주십시오.
- [x] Damselfly 개발 및 테스트
- [x] Damselfly 관련 서브시스템과 통합 테스트 ([Sequence Diagram](https://github.com/cloud-barista/cloud-migrator/blob/main/docs/sequence-diagrams-for-user-scenarios.md) 참고 및 개선)
- [x] Damselfly 실행 지원
- [x] Damselfly 문서화
- [x] Damselfly 릴리스

각 항목별 자세한 사항은 아래 링크의 "저장소별 추진사항"을 참고하시면 될 것 같습니다.
Ref: https://github.com/cloud-barista/cloud-migrator/issues/11

아울러, 릴리스 이후 상위/타 서브시스템에서의 통합 및 테스트가 진행됩니다. 이 부분에 대해 미리 협조를 부탁드립니다.

(참고) 
이번 Cloud-Migrator v0.3.0 통합 및 릴리스는 두 가지 측면에서 진행됩니다.
* 컴퓨팅 인프라 마이그레이션: Cloud-Migration portal에서 3종 클라우드로, 3종 자원에 대해 마이그레이션을 수행할 수 있어야 함
* SW 마이그레이션: 기능 개발, 테스트 및 통합 추진 (portal 통합 대상 X)

**Comment by innodreamer** [comment]
@ish-hcc @dev4unet ( @yunkon-kim )
Damselfly v0.2.1을 release 했습니다.
Damselfly v0.2.0과 비교했을때, 관련 package version으로 cm-model은 v0.0.3을 그대로 유지하고 cb-tumblebug은 v0.10.0로 update 했습니다.
참고로, 현재 cloud Infra model을 위해  cb-tumblebug의 TbMciDynamicReq stucture를 사용하고 있는데 그 struct는 v0.10.0에서 변경되지는 않은 상태입니다.

향후 테스트를 진행하실때 damselfly image v0.2.1 기준으로 테스트를 진행해주시기 바랍니다.

감사합니다.

**Comment by innodreamer** [comment]
@yunkon-kim Butterfly에서 실제 어떤 시나리오로 사용하시는지 확인하고자하는 생각을 가지고 있었습니다.
현재의 sequence diagram 상의 시나리오도 문제는 없으니 위의 checklist에 체크해놨습니다.

**Comment by yunkon-kim** [comment]
@innodreamer (cc. @dev4unet)

사용자 또는 Butterfly 에서의 사용 시나리오와 다른 경우에 업데이트를 위한 PR 올려주십시오. 해당 PR에서 상호 검토 후 반영하도록 하겠습니다.

**Comment by yunkon-kim** [comment]
관련 릴리스: https://github.com/cloud-barista/cm-damselfly/releases/tag/v0.2.1
